# Generated by Django 4.2.3 on 2023-07-19 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelter", "0002_alter_dog_caretakers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="caretakers",
            field=models.ManyToManyField(
                blank=True, related_name="dogs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
