# Generated by Django 4.2.3 on 2023-07-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelter", "0003_alter_dog_caretakers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="dog_size",
            field=models.CharField(
                choices=[
                    ("small", "small"),
                    ("medium", "medium"),
                    ("large", "large"),
                    ("giant", "giant"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
    ]
